server.servlet.contextPath = /bo

server.port = 7878

# management.endpoints.web.exposure.include = *

# Show SQL and format it
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.use_sql_comments=true

# Log SQL via logging system and show bind parameter values
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# Hibernate 6 alternative/extra binder logger (safe to include)
#logging.level.org.hibernate.orm.jdbc.bind=TRACE

#spring.main.lazy-initialization=true
#spring.jmx.enabled=false

#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

#logging.level.org.springframework.web=DEBUG
# Zeigt genaue Timestamps im Log an
logging.pattern.console=%d{yyyy-MM-m HH:mm:ss.SSS} %-5level %logger{36} - %msg%n

server.tomcat.resource-only-jar-scan-configs=true
